# Generated by Django 4.0.6 on 2022-07-23 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juloapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='uuid_staff',
            new_name='uuid_user',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id_wallet', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_wallet', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
    ]
