# Generated by Django 4.0.6 on 2022-07-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juloapi', '0002_rename_uuid_staff_profileuser_uuid_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='time_enabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
