# Generated by Django 4.0.6 on 2022-07-24 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('juloapi', '0003_wallet_time_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id_withdrawal', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_withdrawal', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('time_withdrawal', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juloapi.wallet')),
            ],
            options={
                'db_table': 'withdrawal',
            },
        ),
        migrations.CreateModel(
            name='FundStatement',
            fields=[
                ('id_statement', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_statement', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('time_statement', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('type_fund', models.CharField(max_length=15)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juloapi.wallet')),
            ],
            options={
                'db_table': 'fund_statement',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id_deposit', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_deposit', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('time_deposit', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juloapi.wallet')),
            ],
            options={
                'db_table': 'deposit',
            },
        ),
    ]
