# Generated by Django 4.0.6 on 2022-07-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juloapi', '0004_withdrawal_fundstatement_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juloapi.wallet'),
        ),
        migrations.AlterField(
            model_name='fundstatement',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juloapi.wallet'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juloapi.wallet'),
        ),
    ]
